//
//  Constants.swift
//  SafariExtensionExplorer
//
//  Created by Carlyn Maw on 1/29/24.
//



let extensionName = "SafariExtension"
let goodSamplePage = "https://en.wikipedia.org/wiki/Fish"

#if os(macOS)
//Used by https://developer.apple.com/documentation/safariservices/sfsafariapplication/2202266-showpreferencesforextension
//Autogenerated when creating example code
let extensionBundleIdentifier = "com.carlynorama.SafariExtensionExplorer.SafariExtension"
#endif
